"""
ai_logic
AI prompt builders, rule-based logic modules, schemas, fallbacks,
examples, and test cases for the companion chatbot app.
"""

from .prompts import (
    CHATBOT_SYSTEM_PROMPT,
    build_chat_prompt,
    build_daily_question_prompt,
    build_task_generation_prompt,
    build_profile_analysis_prompt,
    build_task_recommendation_reason_prompt,
    build_friend_recommendation_reason_prompt,
    build_event_feedback_questions_prompt,
    build_event_feedback_score_prompt,
)
from .fallbacks import (
    CHAT_FALLBACK_RESPONSE,
    CRISIS_FALLBACK_RESPONSE,
    SENSITIVE_INFO_FALLBACK_RESPONSE,
    PROFILE_ANALYSIS_FALLBACK,
    TASK_GENERATION_FALLBACK,
    DAILY_QUESTION_FALLBACK,
    FRIEND_REASON_FALLBACK,
    TASK_REASON_FALLBACK,
    get_chat_fallback,
    get_crisis_fallback,
    get_sensitive_info_fallback,
    get_profile_analysis_fallback,
    get_task_generation_fallback,
    get_daily_question_fallback,
    get_friend_reason_fallback,
    get_task_reason_fallback,
    get_event_feedback_questions_fallback,
    get_event_feedback_score_fallback,
)
from .task_logic import (
    get_default_tasks,
    recommend_task,
    recommend_tasks,
    score_task,
    build_task_result,
    normalize_list,
    text_contains_any,
    infer_interest_keywords_from_answers,
)
from .friend_matching import (
    jaccard_similarity,
    conversation_style_score,
    social_style_score,
    calculate_match_score,
    get_shared_interests,
    generate_rule_based_match_reason,
    generate_conversation_starter,
    recommend_friends,
)
from .schemas import (
    ALLOWED_EMOTIONS,
    ALLOWED_NEXT_ACTIONS,
    ALLOWED_INTERESTS,
    ALLOWED_SOCIAL_STYLES,
    ALLOWED_CONVERSATION_STYLES,
    ALLOWED_LONELINESS_LEVELS,
    ALLOWED_TASK_PREFERENCES,
    ALLOWED_TASK_CATEGORIES,
    ALLOWED_DIFFICULTIES,
    ALLOWED_PRESSURE_LEVELS,
    ALLOWED_QUESTION_TYPES,
    CHAT_RESPONSE_SCHEMA,
    DAILY_QUESTION_SCHEMA,
    TASK_GENERATION_SCHEMA,
    PROFILE_ANALYSIS_SCHEMA,
    TASK_REASON_SCHEMA,
    FRIEND_REASON_SCHEMA,
    TASK_SCREEN_SCHEMA,
    GEMINI_TASK_SCREEN_SCHEMA,
)

__all__ = [
    # Prompts
    "CHATBOT_SYSTEM_PROMPT",
    "build_chat_prompt",
    "build_daily_question_prompt",
    "build_task_generation_prompt",
    "build_profile_analysis_prompt",
    "build_task_recommendation_reason_prompt",
    "build_friend_recommendation_reason_prompt",
    # Fallback constants
    "CHAT_FALLBACK_RESPONSE",
    "CRISIS_FALLBACK_RESPONSE",
    "SENSITIVE_INFO_FALLBACK_RESPONSE",
    "PROFILE_ANALYSIS_FALLBACK",
    "TASK_GENERATION_FALLBACK",
    "DAILY_QUESTION_FALLBACK",
    "FRIEND_REASON_FALLBACK",
    "TASK_REASON_FALLBACK",
    # Fallback helpers
    "get_chat_fallback",
    "get_crisis_fallback",
    "get_sensitive_info_fallback",
    "get_profile_analysis_fallback",
    "get_task_generation_fallback",
    "get_daily_question_fallback",
    "get_friend_reason_fallback",
    "get_task_reason_fallback",
    # task_logic
    "get_default_tasks",
    "recommend_task",
    "recommend_tasks",
    "score_task",
    "build_task_result",
    "normalize_list",
    "text_contains_any",
    "infer_interest_keywords_from_answers",
    # friend_matching
    "jaccard_similarity",
    "conversation_style_score",
    "social_style_score",
    "calculate_match_score",
    "get_shared_interests",
    "generate_rule_based_match_reason",
    "generate_conversation_starter",
    "recommend_friends",
    # Schemas and enums
    "ALLOWED_EMOTIONS",
    "ALLOWED_NEXT_ACTIONS",
    "ALLOWED_INTERESTS",
    "ALLOWED_SOCIAL_STYLES",
    "ALLOWED_CONVERSATION_STYLES",
    "ALLOWED_LONELINESS_LEVELS",
    "ALLOWED_TASK_PREFERENCES",
    "ALLOWED_TASK_CATEGORIES",
    "ALLOWED_DIFFICULTIES",
    "ALLOWED_PRESSURE_LEVELS",
    "ALLOWED_QUESTION_TYPES",
    "CHAT_RESPONSE_SCHEMA",
    "DAILY_QUESTION_SCHEMA",
    "TASK_GENERATION_SCHEMA",
    "PROFILE_ANALYSIS_SCHEMA",
    "TASK_REASON_SCHEMA",
    "FRIEND_REASON_SCHEMA",
    "TASK_SCREEN_SCHEMA",
    "GEMINI_TASK_SCREEN_SCHEMA",
]
